name: scone
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2023.05.30
  - certifi=2023.5.7
  - cudatoolkit=10.2.89
  - flit-core=3.6.0
  - intel-openmp=2022.1.0
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuv=1.40.0
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openssl=1.1.1u
  - pip=22.3.1
  - python=3.8.11
  - pytorch=1.9.1
  - readline=8.2
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - tk=8.6.12
  - typing_extensions=4.4.0
  - wheel=0.37.1
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
      - protobuf==3.20.1
      - tensorboardx==2.5.1
      - tqdm==4.65.0
